version: '3.8'

services:
  monitor:
    build: ./monitor
    container_name: monitor-app
    ports:
      - "3000:3000"
    networks:
      - monitor-net

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - monitor-net
      
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./prometheus/targets.json:/etc/prometheus/targets.json
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    env_file:
      - .env
    volumes:
      # Montamos seu arquivo local como template
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.template.yml
    networks:
      - monitor-net
    # O entrypoint abaixo ativa a substituição das variáveis do .env para o arquivo final
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed "s/\$${EMAIL_REMETENTE}/$${EMAIL_REMETENTE}/g; s/\$${SENHA_EMAIL}/$${SENHA_EMAIL}/g" /etc/alertmanager/alertmanager.template.yml > /etc/alertmanager/alertmanager.yml
        /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana-storage:
