scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - 'targets.json'  # Mantenha o Google, GitHub e seu estoque aqui
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115


  - job_name: 'blackbox_dvr'
    metrics_path: /probe
    params:
      module: [tcp_connect] # <--- Aqui está a mágica para o DVR
    static_configs:
      - targets:
          - '206.42.5.52:37777' # <--- COLOQUE A PORTA AQUI (ex: 8000 ou 37777)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
